name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and fix the issue.
        
  - type: textarea
    id: description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Send request to '...'
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: 🌍 Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, Windows 10, macOS 12]
        - Node.js version: [e.g. 18.17.0]
        - API version: [e.g. 1.0.0]
        - Browser: [if applicable]
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: 📋 Error Logs
      description: If applicable, add error logs or API responses
      placeholder: Paste any relevant logs here...
      render: text
      
  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help...
      
  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please confirm you have done the following
      options:
        - label: I have searched for existing issues
          required: true
        - label: I have provided all required information
          required: true
        - label: I have tested this with the latest version
          required: true